### ISSUE TITLE
UI is off-screen on version 3.0.0. Is there a fix for this or did I unknowingly download a bleeding-edge version?

### ISSUE THREAD

**Issue by cilanadzriddle** [MidflightDigital/XX--STARLiGHT--twopointzero#73]
![Image](https://github.com/user-attachments/assets/65b92f53-cd33-4d94-8e6b-0440070b52dc)

I'm on Windows 11, using the latest version of Project Outfox. I have the DanceStages and Characters package implemented if that helps

**Comment by jrom89** [comment]
same issue for me, project outfox and itgmania on macOS 15.3.1

**Comment by Inorizushi** [comment]
Will be taking a look in the next day or two. This is an issue I am aware could've happened due to the OptionsList re-code I worked on.

What's likely happening is that the theme is calling for the OptionsList but it's getting an invalid response.

**Comment by Inorizushi** [comment]
Issued fixed in commit [3b1ae5c](https://github.com/MidflightDigital/XX--STARLiGHT--twopointzero/commit/3b1ae5c33366b6339aa80db8556b70a4a54e3289)

**Comment by Blight607** [comment]
![Image](https://github.com/user-attachments/assets/6186df2b-e85c-4721-9c20-fc60e86d2d21)

I'm having the same issue, and unfortunately even on the latest commit, it is still present.

I tested several different commits, and have confirmed that the bug was introduced in [this commit](https://github.com/MidflightDigital/XX--STARLiGHT--twopointzero/compare/a0fc430c4bdf55f04cf41f6a852c3d6b61dd3677...8da2e8021080ce9e7f61df3fe71ea6567a265b2e) as was predicted.

[Here is the log file produced](https://github.com/user-attachments/files/19822827/ProjectOutfox-XX--STARLiGHT--twopointzero-a0fc430c4bdf55f04cf41f6a852c3d6b61dd3677.ThemeLua.2025-04-19--15.53.30.log) when I tried to open the UI on the version with the bug present.



OS: Ubuntu 22.04.5 LTS
Outfox Version: 0.4.19-LTS

**Comment by Inorizushi** [comment]
I am aware of the issue. I need to get a linux install going as the way I'm checking which OptionsList call to use relies on the product version. (LTS on Windows starts with LTS, it's likely different on other platforms.)

**Comment by Inorizushi** [comment]
https://github.com/MidflightDigital/XX--STARLiGHT--twopointzero/commit/5453a9873d4c409dc835a89ee0ef0bac6fb1c988

Let me know if the issue is fixed on ubuntu with this commit.

**Comment by Blight607** [comment]
I tested the 5453a98 commit, and it did not fix the issue. However, the f114030 commit that came after it did fix it!
I have encountered another bug which crashes the game when the (unmodified) DDR XX simfile pack is loaded, I will try to put out a bug report for it soon!

Thank you!

**Comment by Blight607** [comment]
Just wanted to give an update on the other bug, it was caused by a corrupt group.ini folder within the DDR XX pack off of zenius-vanisher itself. Deleting the folder fixed that issue.

**Comment by Inorizushi** [comment]
Sorry for taking so long with the fix. Turns out there's been a typo in the lua script for the default wheel's screen.

Fixed in https://github.com/MidflightDigital/XX--STARLiGHT--twopointzero/commit/2cbb10cd8abc9f8808f447381290688181f322b6
